---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    # Enable Automatic HTTPS with Let's Encrypt
    - name: Enable HTTPS
      shell: |
        tljh-config set https.enabled true
        tljh-config set https.letsencrypt.email {{ letsencrypt_email }}
        tljh-config unset https.letsencrypt.domains
        tljh-config add-item https.letsencrypt.domains {{ name_server }}

    - name: Reload the proxy
      shell: "tljh-config reload proxy"
